### ISSUE TITLE
How to save imports from works.css

### ISSUE THREAD

**Issue by 10miles** [marxists-org/mass-edits#2]
Hello,
I tried to save this page from marxists.org:
http://www.marxists.org/reference/subject/economics/dilke/1821/sourceandremedy.htm
In Mozila Firefox: Save Page As > Web Page Complte > Save
Web Page saved, but only saved works-blue.css which imports from works.css and latter not saved.
So is there a way to save the page including imports from works.css ?

**Comment by philipmooney** [comment]
I'm sorry, but we don't offer web support via Github issues. This seems to be a question for Mozilla Firefox.
